### ISSUE TITLE
Undefined name 'WorkPriority'

### ISSUE THREAD

**Issue by prilepskiy** [Renesanse/worker_manager#43]
Hello!

I upgraded to 4.2.3version and get an error now:
```
Undefined name 'WorkPriority'.
Try correcting the name to one that is defined, or defining the name.
```

My code:
```
import 'package:worker_manager/worker_manager.dart';

Executor()
    .execute(fun1: getReleaseNotes, arg1: '', priority: WorkPriority.low)
    .then((value) {
      ...
    });
```

But I see that parameter in docs of `execute` method:

```
Cancelable<O> execute<A, B, C, D, O>({
  A arg1,
  B arg2,
  C arg3,
  D arg4,
  FutureOr<O> Function(A) fun1,
  FutureOr<O> Function(A, B) fun2,
  FutureOr<O> Function(A, B, C) fun3,
  FutureOr<O> Function(A, B, C, D) fun4,
  WorkPriority priority = WorkPriority.high,
  bool fake = false,
})
package:worker_manager/src/scheduling/executor.dart
```

How I can use `priority` now?

**Comment by Renesanse** [comment]
Hi, thx for opening the issue, it is a export missing, my bad , sorry

**Comment by Renesanse** [comment]
resolved at https://github.com/Renesanse/worker_manager/pull/44

**Comment by prilepskiy** [comment]
@Renesanse I'm sorry, but I still can't use WorkPriority with 4.2.4

**Comment by Renesanse** [comment]
@prilepskiy Hi, please try 4.2.5

**Comment by prilepskiy** [comment]
Thanks very much, it helped! 🙏
