### ISSUE TITLE
The .cancel function does not work

### ISSUE THREAD

**Issue by Niko-by** [Renesanse/worker_manager#74]
The worker continues to run even after calling the .cancel function

Start the executor
```
final task = Executor().execute(fun1: testFunc, arg1: IsolateModel(100));
await Future.delayed(3.seconds);
print('Run task.cancel');
task.cancel();
```

testFunc
```
FutureOr<Executor?> testFunc(
    IsolateModel model, TypeSendPort<dynamic> port) async {
  for (int i = 1; i < model.cnt; i++) {
    await Future.delayed(1.seconds);
    print('$i');
  }
  return null;
}

class IsolateModel {
  IsolateModel(this.cnt);
  final int cnt;
}
```

Logs
```
1
2
Run taxk.cancel
3
4
5
6
7
8
9
...
```

So, as we can see, after 3 seconds, the .cancel method is fired. I expect the function to be completely stopped and destroyed after this. But she continues to work.

**Comment by Renesanse** [comment]
Hi, thx for opening the issue, I added test case for issue at this commit and slightly modified to handle with CanceledError. https://github.com/Renesanse/worker_manager/commit/b6810bcb80b28246476f1b997c9322abac662fe9.
Can you pls check this out and make sure is there expected behaviour?
Also, can you clarify what environment did you use to run this code?

**Comment by Renesanse** [comment]
From perspective it looks like this: 
![Screenshot 2022-11-08 at 7 05 44 PM](https://user-images.githubusercontent.com/42138594/200641810-d1349cb3-9fa1-470c-b30e-6bcebefc504b.png)

**Comment by Renesanse** [comment]
https://github.com/Renesanse/worker_manager/commit/16f597c2f596b30358174136a1277244a25e7ef7 solved by this commit. Thank you very much for notice this problem!

**Comment by Niko-by** [comment]
I am testing in Flutter WEB

> oh, I see. You didn't use `warmUp` method and here is the problem.

Yes, I tried to add 
```
Executor().warmUp(log: true);
```
Then I get an error and the execution still continues even though the message ``isolate with number -.... killed`` is received

```
1 has been spawned
initialized
added task with number -9007199254740992
isolate with task number -9007199254740992 begins work
1
2
Run task.cancel
isolate with number -9007199254740992 killed
Error: Instance of 'CanceledError'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 299:10  createErrorWithStack
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 341:28            _throw
dart-sdk/lib/core/errors.dart 116:5                                           throwWithStackTrace
dart-sdk/lib/async/zone.dart 1378:11                                          callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
3
4
5
6
7
8
```

Please check WEB version. Or did I miss something?

**Comment by Renesanse** [comment]
Well, yes. You missed something. This lib have not full web support yet. Cause in web to run concurrent code dart team use web workers not an isolates and I don't really now how to stop it correct and parse dart code to js code for web workers. Please, check readme file, there are problem is described. If you have experience in web development and you know how to compile dart code to js for web workers I will be happy to see your implementation. Close for now.

**Comment by Renesanse** [comment]
> I am testing in Flutter WEB
> 
> > oh, I see. You didn't use `warmUp` method and here is the problem.
> 
> Yes, I tried to add
> 
> ```
> Executor().warmUp(log: true);
> ```
> 
> Then I get an error and the execution still continues even though the message `isolate with number -.... killed` is received
> 
> ```
> 1 has been spawned
> initialized
> added task with number -9007199254740992
> isolate with task number -9007199254740992 begins work
> 1
> 2
> Run task.cancel
> isolate with number -9007199254740992 killed
> Error: Instance of 'CanceledError'
> dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 299:10  createErrorWithStack
> dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 341:28            _throw
> dart-sdk/lib/core/errors.dart 116:5                                           throwWithStackTrace
> dart-sdk/lib/async/zone.dart 1378:11                                          callback
> dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
> dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
> dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
> 3
> 4
> 5
> 6
> 7
> 8
> ```
> 
> Please check WEB version. Or did I miss something?

Here https://github.com/Renesanse/worker_manager#warning
